# Generated by Django 5.0.3 on 2024-04-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userlocation_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocation',
            old_name='lang',
            new_name='long',
        ),
    ]
