# Generated by Django 5.0.3 on 2024-04-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_lang_userlocation_long'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlocation',
            unique_together={('user', 'lat', 'long')},
        ),
    ]
