# Generated by Django 5.0.3 on 2024-04-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userlocation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
