# Generated by Django 5.0.3 on 2024-10-14 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=240)),
                ('floor', models.CharField(max_length=10)),
                ('apartment', models.CharField(max_length=10)),
                ('entrance', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('delivered_time', models.DateTimeField()),
                ('is_call', models.BooleanField(default=True)),
                ('subtotal_price', models.FloatField(null=True)),
                ('delivery_price', models.FloatField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'naqd'), ('click', 'click'), ('payme', 'payme'), ('apelsin', 'apelsin')], default='cash', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('prepared', 'Prepared'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], default='created', max_length=10)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userlocation')),
                ('items', models.ManyToManyField(to='orders.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
