# Generated by Django 5.0.3 on 2024-04-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('prepared', 'Prepared'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('finished', 'Finished')], default='created', max_length=10),
        ),
    ]
