# Generated by Django 5.0.3 on 2024-04-11 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userlocation_is_active'),
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userlocation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('prepared', 'Prepared'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], default='created', max_length=10),
        ),
    ]
